---
infraid: 1234
cloudregion: 1234
ldap_ca: certificatecontents
ldap_bind_password: password
ldap_bind_dn: uid=admin,cn=users,dc=example,dc=com
ldap_url: "ldaps://ldap.example.com:636"
ldap_search_url: "{{ ldap_url }}/cn=users,dc=example,dc=com?uid?sub?"
ldap_groups_search_base: cn=groups,dc=example,dc=com
ldap_users_search_base: cn=users,dc=example,dc=com
ldap_groups_whitelist: whitelistcontents
ldap_cron_schedule: "@hourly"

openshift_cluster_content:
- galaxy_requirements: "{{ inventory_dir }}/../requirements.yml"
- object: Cluster Autoscaling
  pre_steps:
    - role: discovery/roles/discover
  content:
  - name: ClusterAutoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
  - name: MachineAutoscaler zone a
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ infraid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}a"
    namespace: openshift-machine-api
  - name: MachineAutoscaler zone b
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ infraid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}b"
    namespace: openshift-machine-api
  - name: MachineAutoscaler zone c
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ infraid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}c"
    namespace: openshift-machine-api
- object: LDAP Cluster Secrets
  content:
  - name: LDAP Secrets
    template: "{{ inventory_dir }}/../templates/ldap-cluster-secrets.yaml"
    params_from_vars:
      LDAP_CA: "{{ ldap_ca }}"
      LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
    namespace: openshift-config
    tags:
    - cluster-secrets
  - name: LDAP Authentication
    template: "{{ inventory_dir }}/../templates/ldap-auth.yaml"
    params_from_vars:
      LDAP_CA: "{{ ldap_ca }}"
      LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
      LDAP_BIND_DN: "{{ ldap_bind_dn }}"
      LDAP_SEARCH_URL: "{{ ldap_search_url }}"
    namespace: openshift-config
    tags:
    - ldap_auth
- object: LDAP Group Synchronization
  content:
  - name: LDAP Group Synchronization
    template: "{{ inventory_dir }}/../templates/ldap-group-sync.yaml"
    params_from_vars:
      LDAP_GROUPS_SEARCH_BASE: "{{ ldap_groups_search_base }}"
      LDAP_BIND_DN: "{{ ldap_bind_dn }}"
      LDAP_URL: "{{ ldap_url }}"
      LDAP_USERS_SEARCH_BASE: "{{ ldap_users_search_base }}"
      LDAP_GROUPS_WHITELIST: "{{ ldap_groups_whitelist }}"
      SCHEDULE: "{{ ldap_cron_schedule }}"
    namespace: openshift-config
    tags:
    - ldap_group_sync
