---
# Exclude cluster-secrets when run from Eunomia GitOps operator
exclude_tags: cluster-secrets

openshift_cluster_content:
- galaxy_requirements: "{{ inventory_dir }}/../requirements.yml"
- object: Setup and Discovery
  pre_steps:
  - role: self/roles/discover
  content:
  - name: GitOps Config
    template: "{{ inventory_dir }}/../templates/cluster-gitops.yaml"
    tags:
    - gitops
- object: OpenShift Machine API
  content:
  - name: Custom Machinesets
    file: "{{ inventory_dir }}/../templates/custom-machinesets.j2"
    tags:
    - openshift-machine-api
  - name: Default Machinesets
    file: "{{ inventory_dir }}/../templates/default-machinesets.j2"
    tags:
    - openshift-machine-api
    post_steps:
    - role: self/roles/openshift_machine_api
  - name: Cluster Autoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
- object: Scheduler
  content:
  - name: Cluster Autoscaler
    file: "{{ inventory_dir }}/../templates/scheduler.j2"
- object: LDAP Cluster Secrets
  content:
  - name: LDAP Secrets
    template: "{{ inventory_dir }}/../templates/ldap-cluster-secrets.yaml"
    params_from_vars:
      LDAP_CA: "{{ ldap_ca }}"
      LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
    namespace: openshift-config
    tags:
    - cluster-secrets
  - name: LDAP Authentication
    template: "{{ inventory_dir }}/../templates/ldap-auth.yaml"
    params_from_vars:
      LDAP_CA: "{{ ldap_ca }}"
      LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
      LDAP_BIND_DN: "{{ ldap_bind_dn }}"
      LDAP_SEARCH_URL: "{{ ldap_search_url }}"
    namespace: openshift-config
    tags:
    - ldap_auth
- object: LDAP Group Synchronization
  content:
  - name: LDAP Group Synchronization
    template: "{{ inventory_dir }}/../templates/ldap-group-sync.yaml"
    params_from_vars:
      LDAP_GROUPS_SEARCH_BASE: "{{ ldap_groups_search_base }}"
      LDAP_BIND_DN: "{{ ldap_bind_dn }}"
      LDAP_URL: "{{ ldap_url }}"
      LDAP_USERS_SEARCH_BASE: "{{ ldap_users_search_base }}"
      LDAP_GROUPS_WHITELIST: "{{ ldap_groups_whitelist | default('') }}"
      SCHEDULE: "{{ ldap_cron_schedule }}"
    namespace: openshift-config
    tags:
    - ldap_group_sync
- object: Setup AWS StorageClasses
  content:
  - name: Setup AWS StorageClasses
    template: "{{ inventory_dir }}/../templates/aws-ebs-storage-classes.yaml"
    params_from_vars:
      ENCRYPT_STORAGE: "{{ aws_sc_encrypt_storage }}"
    namespace: openshift-config
    tags:
    - aws
    - aws-storage-classes
- object: Configure Project Creation
  content:
  # Deploys the Namespace Configuration Operator
  # https://github.com/redhat-cop/namespace-configuration-operator/
  - name: Namespace Config Operator Namespace
    file: "{{ inventory_dir }}/../manifests/namespace-config-operator-ns.yaml"
    tags:
    - project-config
  - name: Namespace Config Operator CRD
    file: https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/v0.0.1/deploy/crds/redhatcop_v1alpha1_namespaceconfig_crd.yaml
    namespace: namespace-configuration-operator
    tags:
    - project-config
  - name: Namespace Config Operator Role
    file: https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/v0.0.1/deploy/role.yaml
    namespace: namespace-configuration-operator
    tags:
    - project-config
  - name: Namespace Config Operator Role Binding
    file: https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/v0.0.1/deploy/role_binding.yaml
    namespace: namespace-configuration-operator
    tags:
    - project-config
  - name: Namespace Config Operator Service Account
    file: https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/v0.0.1/deploy/service_account.yaml
    namespace: namespace-configuration-operator
    tags:
    - project-config
  - name: Namespace Config Operator Deployment
    file: https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/v0.0.1/deploy/operator.yaml
    namespace: namespace-configuration-operator
    tags:
    - project-config
  # Deploys the Onboarding Operator
  # https://github.com/redhat-cop/onboarding-manager
  - name: Project Configurations
    file: "{{ inventory_dir }}/../manifests/project-config/"
    tags:
    - project-config
  - name: Projects for Onboarded Applications
    file: "{{ inventory_dir }}/../manifests/apps/"
    tags:
    - project-config



# Variables set dynamically by set_fact in discover role
infraid: ''
cloudregion: ''
